### PR TITLE
Fix setup

### PR DESCRIPTION
**Pull request by jennan**
Add more instructions for installation & utilisation on NeSI (screenshots & pre-configured conda environment).

The virtual environment is stored in `/nesi/project/nesi99991/snakemake20210914/snakemake_env`, which is accessible to all registered users (part of training account nesi99991).

### CODE REVIEW

**Comment by chrisdjscott** [comment]
@jennan looks good. Regarding the preconfigured conda environment, that will only work if they are a member of nesi99991. For example, if somebody else tries to follow that instruction, or if a workshop attendee tries to follow it in their own project later on, that step won't work. Should we put a note about this with a link to the section about setting up the conda env? On the other hand, creating the conda environment themselves is only a single command and won't take long, so maybe could just ask them to do that to avoid confusion?

**Comment by jennan** [comment]
@chrisdjscott if they create the virtual environment themselves we need to:
- put back the instructions to add the channels in their .condarc
- make sure they install mamba too (otherwise --use-conda will cause issues in section 03)
- decide where they install their environment, because home very likely not big enough for the venv (if they have other things in it it will run out of space)

**Comment by chrisdjscott** [comment]
@jennan , is installing mamba just a case of adding it to the conda create command? We could get them to run in the project or nobackup directory (would just be a cd at the beginning and a different conda command to specify the path?). To me it seems better to do something they can reuse in their own project later but if it creates more work for us / more risk of things going wrong maybe not worth it.

**Comment by jennan** [comment]
@chrisdjscott yes, for mamba that should do the job to add it in the conda create :).

For the cd at the beginning, something like this
```
cd /nesi/nesi99991/snakemake20210914
mkdir $USER
cd $USER
```
to ensure they have their own folder?

**Comment by jennan** [comment]
@DininduSenanayake @chrisdjscott I won't have time to update this PR before tonight, please feel free to edit it before if needed (do I need to change something to allow edition from you btw?).

**Comment by chrisdjscott** [comment]
I'll accept, may need to tweak or change back to using your prebuilt depending on what others thing. Also, there were some conflicts to fix, might not have got it quite right

**Pull request merged**
