### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by leahkemp**
A few small changes/tweaks

- Fixes/changes to page navigation buttons
- Continue to deploy workflow to slurm in section 04 after slurm section
- Clean up slurm log files as the workshop progresses
- Remove an intentional error in the workshop that produced surprising/unwanted results when run on NeSi
- Dag number ordering 🙃

### CODE REVIEW

**Comment by leahkemp** [comment]
See rendered github page of changes:

https://leahkemp.github.io/snakemake_workshop/workshop_material/01_introduction.html
https://leahkemp.github.io/snakemake_workshop/workshop_material/02_setup.html
https://leahkemp.github.io/snakemake_workshop/workshop_material/03_create_a_basic_workflow.html
https://leahkemp.github.io/snakemake_workshop/workshop_material/04_leveling_up_your_workflow.html
https://leahkemp.github.io/snakemake_workshop/workshop_material/05_we_want_more.html

**Comment by jennan** [comment]
Arg... I have merged too fast :D. @leahkemp are you planning to add the numbered dag files in the basic_demo_workflow folder (+ README)?

**Comment by leahkemp** [comment]
Oh good point, that didn't even occur to me 🙃 we could update that in the final sweep to update all the output files? ie. during this task: https://github.com/nesi/snakemake_workshop/projects/2#card-81506759

**Comment by jennan** [comment]
Yep let's do this :-).

**Pull request merged**
