### PR TITLE
Enhanced hpc

### PR DESCRIPTION
**Pull request by jennan**
Additional goodies for the Slurm profile

- allow job cancellation
- make snakemake track slurm job status
- put Slurm logs in a dedicated folder (and name logs according to rule and jobID)
- use multiline in the profile for increased readability of the (long) sbatch command
- add output files for slurm profile

### CODE REVIEW

**Comment by leahkemp** [comment]
Hello @jennan ! Did you intend to include the slurm config file at [demo_workflow/workflow/slurm/config.yaml](https://github.com/nesi/snakemake_workshop/blob/enhanced_hpc/demo_workflow/workflow/slurm/config.yaml) in the PR? If so we might want to modify the start of [section 4.1](https://nesi.github.io/snakemake_workshop/workshop_material/04_leveling_up_your_workflow.html#41-use-a-profile-for-hpc) which is still instructing the workshop taker to create and write to this file :)

**Comment by jennan** [comment]
Woops @leahkemp this file shouldn't be there... I have probably committed this one thinking I was in the leveled_up workflow folder. I'll remove it.

**Comment by leahkemp** [comment]
Just updated the path to `--output` for writing the slurm log files so they are consistent throughout :)

**Review by leahkemp — APPROVED** [review]
Nice! Glad to have heaps of useful slurm stuff in the workshop, I need to update my snakemake stuff with these slurm deployment tricks :)

**Pull request merged**
